defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
  values:
    layout: "default"
url: "dwdwdan.github.io"
baseurl: /recipes

plugins:
  - jekyll-feed

title: "Dan's Recipes"
description: "Where I store and collate recipes"
url: "https://dwdwdan.github.io/recipes/"
