defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
  values:
    layout: "default"
url: "recipes.dwdwdan.xyz"
baseurl:

plugins:
  - jekyll-feed

title: "Dan's Recipes"
description: "Where I store and collate recipes"
url: "https://dwdwdan.github.io/recipes/"
